#!/bin/bash

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc set_font    "Dina-10"
berryc move_mask   "mod4"
berryc resize_mask "mod1"
berryc edge_lock   "false"

#start hotkey daemon
killall -q sxhkd
sxhkd -c ~/.config/berry/sxhkdrc &
disown

# set wallpaper
nitrogen --restore
